# ????????? multipart ????????
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

# ????????? ?????????? ??? ???????? ??????
spring.servlet.multipart.location=${java.io.tmpdir}

# ????????? ????????? Tomcat ??? multipart, ??? ??? ?????????? Spring
server.tomcat.max-http-form-post-size=-1

server.port=8081
spring.web.resources.static-locations=file:uploads/